// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPart.proto

package dk.via.slaughterhouse.protobuf.animalpart;

public interface CreateAnimalPartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.animalpart.CreateAnimalPartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weight = 1;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>int64 animalId = 2;</code>
   * @return The animalId.
   */
  long getAnimalId();

  /**
   * <code>int64 animalPartTypeId = 3;</code>
   * @return The animalPartTypeId.
   */
  long getAnimalPartTypeId();

  /**
   * <code>int64 trayId = 4;</code>
   * @return The trayId.
   */
  long getTrayId();

  /**
   * <code>int64 productId = 5;</code>
   * @return The productId.
   */
  long getProductId();
}
