// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPart.proto

package dk.via.slaughterhouse.protobuf.animalpart;

public interface GetAnimalPartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.animalpart.GetAnimalPartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
