// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalType.proto

package dk.via.slaughterhouse.protobuf.animaltype;

public interface GetAnimalTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.animaltype.GetAnimalTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
