// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package dk.via.slaughterhouse.protobuf.animal;

public final class Animal {
  private Animal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Animal.proto\022%dk.via.slaughterhouse.pr" +
      "otobuf.animal\"U\n\023CreateAnimalRequest\022\024\n\014" +
      "animalTypeId\030\001 \001(\003\022\016\n\006weight\030\002 \001(\001\022\030\n\020re" +
      "gistrationDate\030\003 \001(\t\",\n\024CreateAnimalResp" +
      "onse\022\024\n\014confirmation\030\001 \001(\t\"$\n\020GetAnimalR" +
      "equest\022\020\n\010animalId\030\001 \001(\003\"e\n\021GetAnimalRes" +
      "ponse\022\020\n\010animalId\030\001 \001(\003\022\024\n\014animalTypeId\030" +
      "\002 \001(\003\022\016\n\006weight\030\003 \001(\001\022\030\n\020registrationDat" +
      "e\030\004 \001(\t\"(\n\023GetAnimalIdsRequest\022\021\n\tproduc" +
      "tId\030\001 \001(\003\")\n\024GetAnimalIdsResponse\022\021\n\tani" +
      "malIds\030\001 \003(\0032\243\003\n\rAnimalService\022\207\001\n\014creat" +
      "eAnimal\022:.dk.via.slaughterhouse.protobuf" +
      ".animal.CreateAnimalRequest\032;.dk.via.sla" +
      "ughterhouse.protobuf.animal.CreateAnimal" +
      "Response\022~\n\tgetAnimal\0227.dk.via.slaughter" +
      "house.protobuf.animal.GetAnimalRequest\0328" +
      ".dk.via.slaughterhouse.protobuf.animal.G" +
      "etAnimalResponse\022\207\001\n\014getAnimalIds\022:.dk.v" +
      "ia.slaughterhouse.protobuf.animal.GetAni" +
      "malIdsRequest\032;.dk.via.slaughterhouse.pr" +
      "otobuf.animal.GetAnimalIdsResponseB\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalRequest_descriptor,
        new java.lang.String[] { "AnimalTypeId", "Weight", "RegistrationDate", });
    internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animal_CreateAnimalResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalResponse_descriptor,
        new java.lang.String[] { "AnimalId", "AnimalTypeId", "Weight", "RegistrationDate", });
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsResponse_descriptor,
        new java.lang.String[] { "AnimalIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
