// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package dk.via.slaughterhouse.protobuf.animal;

/**
 * Protobuf type {@code dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest}
 */
public final class GetAnimalIdsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)
    GetAnimalIdsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAnimalIdsRequest.newBuilder() to construct.
  private GetAnimalIdsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAnimalIdsRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAnimalIdsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAnimalIdsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            productId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.slaughterhouse.protobuf.animal.Animal.internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.slaughterhouse.protobuf.animal.Animal.internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest.class, dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest.Builder.class);
  }

  public static final int PRODUCTID_FIELD_NUMBER = 1;
  private long productId_;
  /**
   * <code>int64 productId = 1;</code>
   * @return The productId.
   */
  @java.lang.Override
  public long getProductId() {
    return productId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (productId_ != 0L) {
      output.writeInt64(1, productId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (productId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, productId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)) {
      return super.equals(obj);
    }
    dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest other = (dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest) obj;

    if (getProductId()
        != other.getProductId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProductId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)
      dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.slaughterhouse.protobuf.animal.Animal.internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.slaughterhouse.protobuf.animal.Animal.internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest.class, dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest.Builder.class);
    }

    // Construct using dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.slaughterhouse.protobuf.animal.Animal.internal_static_dk_via_slaughterhouse_protobuf_animal_GetAnimalIdsRequest_descriptor;
    }

    @java.lang.Override
    public dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest getDefaultInstanceForType() {
      return dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest build() {
      dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest buildPartial() {
      dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest result = new dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest(this);
      result.productId_ = productId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest) {
        return mergeFrom((dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest other) {
      if (other == dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest.getDefaultInstance()) return this;
      if (other.getProductId() != 0L) {
        setProductId(other.getProductId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long productId_ ;
    /**
     * <code>int64 productId = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId_;
    }
    /**
     * <code>int64 productId = 1;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(long value) {
      
      productId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 productId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      
      productId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)
  }

  // @@protoc_insertion_point(class_scope:dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)
  private static final dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest();
  }

  public static dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAnimalIdsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetAnimalIdsRequest>() {
    @java.lang.Override
    public GetAnimalIdsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAnimalIdsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAnimalIdsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAnimalIdsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

