// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package dk.via.slaughterhouse.protobuf.animal;

public interface GetAnimalIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 productId = 1;</code>
   * @return The productId.
   */
  long getProductId();
}
