// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package dk.via.slaughterhouse.protobuf.animal;

public interface GetAnimalIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.animal.GetAnimalIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 animalIds = 1;</code>
   * @return A list containing the animalIds.
   */
  java.util.List<java.lang.Long> getAnimalIdsList();
  /**
   * <code>repeated int64 animalIds = 1;</code>
   * @return The count of animalIds.
   */
  int getAnimalIdsCount();
  /**
   * <code>repeated int64 animalIds = 1;</code>
   * @param index The index of the element to return.
   * @return The animalIds at the given index.
   */
  long getAnimalIds(int index);
}
