// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Animal.proto

package dk.via.slaughterhouse.protobuf.animal;

public interface GetAnimalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.animal.GetAnimalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 animalId = 1;</code>
   * @return The animalId.
   */
  long getAnimalId();
}
