// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package dk.via.slaughterhouse.protobuf.product;

public interface GetProductIdsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.product.GetProductIdsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 animalId = 1;</code>
   * @return The animalId.
   */
  long getAnimalId();
}
