// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package dk.via.slaughterhouse.protobuf.product;

public interface GetProductIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.product.GetProductIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 productIds = 1;</code>
   * @return A list containing the productIds.
   */
  java.util.List<java.lang.Long> getProductIdsList();
  /**
   * <code>repeated int64 productIds = 1;</code>
   * @return The count of productIds.
   */
  int getProductIdsCount();
  /**
   * <code>repeated int64 productIds = 1;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  long getProductIds(int index);
}
