// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package dk.via.slaughterhouse.protobuf.product;

public interface GetProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.product.GetProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
