// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Product.proto

package dk.via.slaughterhouse.protobuf.product;

public final class Product {
  private Product() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_product_GetProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_product_GetProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProduct.proto\022&dk.via.slaughterhouse.p" +
      "rotobuf.product\"I\n\024CreateProductRequest\022" +
      "\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\016\n\006tr" +
      "ayId\030\003 \001(\003\"-\n\025CreateProductResponse\022\024\n\014c" +
      "onfirmation\030\001 \001(\t\"\037\n\021GetProductRequest\022\n" +
      "\n\002id\030\001 \001(\003\"k\n\022GetProductResponse\022\n\n\002id\030\001" +
      " \001(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022" +
      "\026\n\016animalPartsIds\030\004 \003(\003\022\016\n\006trayId\030\005 \001(\003\"" +
      "(\n\024GetProductIdsRequest\022\020\n\010animalId\030\001 \001(" +
      "\003\"+\n\025GetProductIdsResponse\022\022\n\nproductIds" +
      "\030\001 \003(\0032\264\003\n\016ProductService\022\214\001\n\rcreateProd" +
      "uct\022<.dk.via.slaughterhouse.protobuf.pro" +
      "duct.CreateProductRequest\032=.dk.via.slaug" +
      "hterhouse.protobuf.product.CreateProduct" +
      "Response\022\203\001\n\ngetProduct\0229.dk.via.slaught" +
      "erhouse.protobuf.product.GetProductReque" +
      "st\032:.dk.via.slaughterhouse.protobuf.prod" +
      "uct.GetProductResponse\022\214\001\n\rgetProductIds" +
      "\022<.dk.via.slaughterhouse.protobuf.produc" +
      "t.GetProductIdsRequest\032=.dk.via.slaughte" +
      "rhouse.protobuf.product.GetProductIdsRes" +
      "ponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "TrayId", });
    internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_product_CreateProductResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_product_GetProductRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_product_GetProductResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "AnimalPartsIds", "TrayId", });
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsRequest_descriptor,
        new java.lang.String[] { "AnimalId", });
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_product_GetProductIdsResponse_descriptor,
        new java.lang.String[] { "ProductIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
