// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPartType.proto

package dk.via.slaughterhouse.protobuf.animalparttype;

public final class AnimalPartType {
  private AnimalPartType() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024AnimalPartType.proto\022-dk.via.slaughter" +
      "house.protobuf.animalparttype\"@\n\033CreateA" +
      "nimalPartTypeRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013de" +
      "scription\030\002 \001(\t\"4\n\034CreateAnimalPartTypeR" +
      "esponse\022\024\n\014confirmation\030\001 \001(\t\"&\n\030GetAnim" +
      "alPartTypeRequest\022\n\n\002id\030\001 \001(\003\"J\n\031GetAnim" +
      "alPartTypeResponse\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002" +
      " \001(\t\022\023\n\013description\030\003 \001(\t2\362\002\n\025AnimalPart" +
      "TypeService\022\257\001\n\024createAnimalPartType\022J.d" +
      "k.via.slaughterhouse.protobuf.animalpart" +
      "type.CreateAnimalPartTypeRequest\032K.dk.vi" +
      "a.slaughterhouse.protobuf.animalparttype" +
      ".CreateAnimalPartTypeResponse\022\246\001\n\021getAni" +
      "malPartType\022G.dk.via.slaughterhouse.prot" +
      "obuf.animalparttype.GetAnimalPartTypeReq" +
      "uest\032H.dk.via.slaughterhouse.protobuf.an" +
      "imalparttype.GetAnimalPartTypeResponseB\002" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Name", "Description", });
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animalparttype_CreateAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dk_via_slaughterhouse_protobuf_animalparttype_GetAnimalPartTypeResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
