// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnimalPartType.proto

package dk.via.slaughterhouse.protobuf.animalparttype;

public interface GetAnimalPartTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.animalparttype.GetAnimalPartTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
