// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tray.proto

package dk.via.slaughterhouse.protobuf.tray;

public interface GetTrayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.slaughterhouse.protobuf.tray.GetTrayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
